set_property PACKAGE_PIN L1 [get_ports {Q[2]}]
set_property PACKAGE_PIN P1 [get_ports {Q[1]}]
set_property PACKAGE_PIN N3 [get_ports {Q[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Q[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN R2 [get_ports en]
set_property PACKAGE_PIN T1 [get_ports rstn]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports rstn]

create_clock -period 10.000 -name sys_clk -waveform {0 5} [get_ports clk]
